# Generated by Django 4.2.7 on 2025-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('product_imported', 'Product Imported'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('all_products_deleted', 'All Products Deleted')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
                'indexes': [models.Index(fields=['event_type'], name='webhooks_event_t_3d1bb2_idx'), models.Index(fields=['is_active'], name='webhooks_is_acti_7ab6f5_idx'), models.Index(fields=['created_at'], name='webhooks_created_913b65_idx')],
            },
        ),
    ]
