# Generated by Django 4.2.7 on 2025-11-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_name'),
    ]

    operations = [
    ]
